-- 코드를 입력하세요
SELECT USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS '전체주소', 
    CASE LENGTH(U.TLNO)
        WHEN 10
        THEN CONCAT(LEFT(U.TLNO, 3), '-', MID(U.TLNO, 4, 3), '-', RIGHT(U.TLNO, 4))
        WHEN 11
        THEN CONCAT(LEFT(U.TLNO, 3), '-', MID(U.TLNO, 4, 4), '-', RIGHT(U.TLNO, 4))
    END AS '전화번호'
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON WRITER_ID = USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC