-- 코드를 입력하세요
SELECT  A.ID, A.NAME, A.HOST_ID
FROM PLACES A,(
    SELECT ID, NAME, HOST_ID, COUNT(HOST_ID) AS CNT 
    FROM PLACES 
    GROUP BY HOST_ID 
    HAVING CNT >= 2) B
WHERE A.HOST_ID = B.HOST_ID
ORDER BY A.ID;